### ISSUE TITLE
Не резолвится имя SIP сервера

### ISSUE THREAD

**Issue by mirackle-spb** [rosteleset/SmartYard-Android#1]
Если в push передавать в поле server любое имя отличное от baseUrl - попытка Linphone зарегистрироваться в спящем режиме, когда приложение не находится на экране проваливается с ошибкой:
D/Ringtone: Successfully created local player
I/LinphoneService: debug_dmm message: ProxyConfig already entered, ignored.
I/LinphoneService: debug_dmm message: resolver_process_data dns_res_check() error: Operation not permitted (1)
I/LinphoneService: debug_dmm message: resolver_process_data dns_res_check() error: Operation not permitted (1)
I/LinphoneService: debug_dmm message: resolver_process_data dns_res_check() error: Operation not permitted (1)
I/LinphoneService: debug_dmm message: channel_res_done: DNS resolution failed for  mz57.dm-voice.xx.ru
D/LinphoneProvider$mCoreListener: debug_dmm reg_state: Progress message: Registration in progress
D/LinphoneProvider$mCoreListener: debug_dmm reg_state: Failed message: io error
I/LinphoneService: debug_dmm message: resolver_process_data dns_res_check() error: Operation not permitted (1)
I/LinphoneService: debug_dmm message: resolver_process_data dns_res_check() error: Operation not permitted (1)
I/LinphoneService: debug_dmm message: resolver_process_data dns_res_check() error: Operation not permitted (1)
I/LinphoneService: debug_dmm message: channel_res_done: DNS resolution failed for mz57.dm-voice.xx.ru

Прт этом в эмуляторе все работает хорошо. А вот в реальном девайсе вылетает в ошибки.

**Comment by mirackle-spb** [comment]
Если отдавать прямиком ip адрес - получаем ошибку:
I/LinphoneService: debug_dmm message: Connection failed  for fd [120]: cause [Connection timed out]
I/LinphoneService: debug_dmm message: Cannot connect to [TCP://5.8.36.40:5060]
D/LinphoneProvider$mCoreListener: debug_dmm reg_state: Failed message: io error

Samsung S21

**Comment by alexeimenshikh** [comment]
Какая версия Android на эмуляторе и реальном устройстве?

**Comment by mirackle-spb** [comment]
на телефоне 12 андроид.
В эмуляторе API 32

**Comment by alexeimenshikh** [comment]
Можете прислать содержимое push, чтобы мы у себя попытались воспроизвести проблему?
