### ISSUE TITLE
При загрузке настроек адреса выполняется 2 запроса, вместо одного

### ISSUE THREAD

**Issue by mirackle-spb** [rosteleset/SmartYard-Android#2]
При загрузке данных настроек адреса, приложение выполняет запрос /intercom с указанным flatId.

После чего, сразу же выполняется запрос на установление whiteRabbit в значение, переданное в предыдущем ответе.
Вероятно где-то лишний раз срабатывает onChange при установке полученных от сервера значений, что и вызывает срабатывание листенера.

Лог обмена в момент нажатия на кнопку "Настройки адреса" прилагаю.

**Comment by mirackle-spb** [comment]
[console-output.txt](https://github.com/rosteleset/SmartYard-Android/files/11676761/console-output.txt)

**Comment by alexeimenshikh** [comment]
Да, это так из-за того, что в API используется один и тот же метод для установки и чтения значений intercom.
Если значения (это относится не только к whiteRabbit) отличаются от принятых по-умолчанию, то метод intercom будет вызван многократно. Я пока не планирую менять из-за этого логику обработки метода intercom.
